# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d
###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###


# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "title": "Билет на концерт Metallica",
  "description": "Билеты до Америки в стоимость не включены"
}

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "title": "Depeche Mode пластинки",
  "description": "Enjoy the Silence..."
}

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "title": "Футболка Найк",
  "description": "Не Борзов"
}

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "title": "Собрник книг о Ленине",
  "description": "Путь Ленина и исследования ученых на тему 'Ленин - гриб'"
}

###
# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "title": "Книга 'Автостопом по галактике'",
  "description": "Путеводитель дешево"
}

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "title": "Продам гараж",
  "description": "Кассета с фильмом 'Гараж', 1980 год"
}

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "title": "Куплю щенка",
  "description": "Люблю щенков"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/4/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "status": "OPEN"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/4/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2024-01-12
Content-Type: application/json
